name = "image-search-hub"
compatibility_date = "2026-09-16"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "image-search-hub-temp"

[vars]
# Temporary images expire in the application after 10 minutes.
