import { engines, selectedEngines } from './engines/registry.js';
import { normalizeImage, rotateImage } from './image/processor.js';
import { addHistory } from './storage/indexeddb.js';

const state={original:null,image:null,objectUrl:null,rotation:0};
const $=id=>document.getElementById(id);
const els={file:$('fileInput'),drop:$('dropzone'),pick:$('pickBtn'),empty:$('emptyState'),previewState:$('previewState'),preview:$('preview'),name:$('imageName'),info:$('imageInfo'),status:$('inputStatus'),url:$('urlInput'),loadUrl:$('loadUrl'),clear:$('clearBtn'),grid:$('engineGrid'),selected:$('searchSelected'),all:$('searchAll'),results:$('results'),hint:$('actionHint'),theme:$('themeToggle'),left:$('rotateLeft'),right:$('rotateRight'),reset:$('resetBtn'),selectAll:$('selectAll'),selectNone:$('selectNone')};

function initTheme(){const saved=localStorage.getItem('ish-theme');const dark=saved==='dark'||(!saved&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';els.theme.textContent=dark?'☀':'☾';}
function renderEngines(){els.grid.replaceChildren(...engines.map((e,i)=>{const label=document.createElement('label');label.className='engine';label.innerHTML=`<input type="checkbox" data-engine="${e.id}" ${i<4?'checked':''}><div class="engine-body"><div class="engine-title"><strong>${e.name}</strong><span class="badge">${e.badge}</span></div><span class="engine-desc">${e.description}</span><span class="mode">${e.mode==='url'?'⚡ 圖片 URL 可直接啟動':'↗ 開啟網站後手動上傳'}</span></div>`;return label;}));updateHint();}
function checkedIds(){return [...els.grid.querySelectorAll('input[data-engine]:checked')].map(x=>x.dataset.engine)}
function updateHint(){const n=checkedIds().length;els.hint.textContent=n?`已選 ${n} 個引擎。URL 型引擎可直接帶入圖片；其餘會開啟上傳頁。`:'至少選擇一個搜尋引擎。';}
function setStatus(text,ok=false){els.status.textContent=text;els.status.style.color=ok?'var(--primary)':'var(--muted)'}
async function setImage(file,name=file.name){
  if(!(file instanceof Blob)||!file.type?.startsWith('image/')){setStatus('請選擇有效的圖片檔。');return;}
  try{setStatus('正在處理圖片…');state.original=file;state.rotation=0;state.image=await normalizeImage(file);if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);state.objectUrl=URL.createObjectURL(state.image.blob);els.preview.src=state.objectUrl;els.name.textContent=name||'貼上的圖片';els.info.textContent=`${state.image.width} × ${state.image.height} · WebP · 已移除原始 EXIF`;els.empty.classList.add('hidden');els.previewState.classList.remove('hidden');els.clear.classList.remove('hidden');setStatus('圖片已準備完成。',true);}catch(err){setStatus(err.message||'圖片處理失敗。');}}
function clearImage(){state.original=null;state.image=null;state.rotation=0;if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);state.objectUrl=null;els.preview.removeAttribute('src');els.empty.classList.remove('hidden');els.previewState.classList.add('hidden');els.clear.classList.add('hidden');setStatus('');}
async function loadFromUrl(){const url=els.url.value.trim();if(!/^https?:\/\//i.test(url)){setStatus('請輸入 http:// 或 https:// 的圖片網址。');return}try{setStatus('正在下載圖片到瀏覽器…');const r=await fetch(url,{mode:'cors'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=await r.blob();await setImage(b,url.split('/').pop()||'URL image');}catch(err){setStatus('此圖片網址無法由瀏覽器直接讀取（可能是 CORS 或防盜鏈）。可保留網址並手動開啟搜尋引擎。');}}
function openPopup(url){const w=window.open(url,'_blank','noopener,noreferrer');return !!w;}
async function searchOne(engine){const hasImage=!!state.image?.blob;let url=engine.buildManualUrl();let method='manual';if(hasImage&&engine.mode==='url'){url=engine.buildUrl(location.origin.includes('localhost')?'':null);method='manual';}
  // URL engines need a publicly reachable URL. V1 deliberately does not upload files to a third party from our app.
  // When the source itself is already a URL, use it directly; local files open the engine's manual upload page.
  const sourceUrl=els.url.value.trim(); if(sourceUrl&&/^https?:\/\//i.test(sourceUrl)&&engine.mode==='url'){url=engine.buildUrl(sourceUrl);method='url';}
  const opened=openPopup(url);return {engine,opened,method,url};}
async function runSearch(ids){if(!ids.length){setStatus('請至少選擇一個搜尋引擎。');return}if(!state.image?.blob&&!els.url.value.trim()){setStatus('請先加入圖片。');return}
els.results.replaceChildren();const selected=selectedEngines(ids);for(const engine of selected){const row=document.createElement('div');row.className='result';const main=document.createElement('div');main.className='result-main';const title=document.createElement('strong');title.textContent=engine.name;const sub=document.createElement('span');sub.textContent=engine.mode==='url'&&els.url.value.trim()?'嘗試以圖片 URL 開啟搜尋':'開啟搜尋頁後手動上傳圖片';main.append(title,sub);const button=document.createElement('button');button.className='secondary';button.type='button';button.textContent='開啟';row.append(main,button);els.results.append(row);button.addEventListener('click',async()=>{const r=await searchOne(engine);sub.textContent=r.opened?(r.method==='url'?'已以圖片 URL 開啟':'已開啟，請在網站完成圖片上傳'):'瀏覽器阻擋新視窗，請允許彈出視窗';});const r=await searchOne(engine);sub.textContent=r.opened?(r.method==='url'?'已開啟圖片 URL 搜尋':'已開啟搜尋頁，請上傳圖片'):'新視窗被瀏覽器阻擋';}
await addHistory({engines:ids,type:state.original?'file':'url'});}

els.pick.addEventListener('click',e=>{e.stopPropagation();els.file.click()});els.drop.addEventListener('click',e=>{if(e.target===els.drop||e.target.closest('.empty-state'))els.file.click()});els.drop.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target===els.drop){e.preventDefault();els.file.click()}});els.file.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)setImage(f)});
['dragenter','dragover'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.remove('dragover')}));els.drop.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)setImage(f)});
document.addEventListener('paste',e=>{const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith('image/'));if(item)setImage(item.getAsFile(),'Clipboard image')});els.loadUrl.addEventListener('click',loadFromUrl);els.url.addEventListener('keydown',e=>{if(e.key==='Enter')loadFromUrl()});els.clear.addEventListener('click',clearImage);els.selectAll.addEventListener('click',()=>{els.grid.querySelectorAll('input').forEach(x=>x.checked=true);updateHint()});els.selectNone.addEventListener('click',()=>{els.grid.querySelectorAll('input').forEach(x=>x.checked=false);updateHint()});els.grid.addEventListener('change',updateHint);els.selected.addEventListener('click',()=>runSearch(checkedIds()));els.all.addEventListener('click',()=>{els.grid.querySelectorAll('input').forEach(x=>x.checked=true);updateHint();runSearch(checkedIds())});
els.left.addEventListener('click',async()=>{if(!state.image)return;state.image=await rotateImage(state.image.blob,-90);state.rotation-=90;els.preview.src=URL.createObjectURL(state.image.blob);els.info.textContent=`${state.image.width} × ${state.image.height} · WebP · 已處理`;});els.right.addEventListener('click',async()=>{if(!state.image)return;state.image=await rotateImage(state.image.blob,90);state.rotation+=90;els.preview.src=URL.createObjectURL(state.image.blob);els.info.textContent=`${state.image.width} × ${state.image.height} · WebP · 已處理`;});els.reset.addEventListener('click',()=>state.original&&setImage(state.original,els.name.textContent));
els.theme.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';els.theme.textContent=dark?'☀':'☾';localStorage.setItem('ish-theme',dark?'dark':'light')});

initTheme();renderEngines();
